### PR TITLE
Update headers and libraries for 64 bit linux/macos(arm)/windows

### PR DESCRIPTION
**Pull request by eddelbuettel**
This updates the binary artifacts for 64 operating systems
- linux
- macos (arm64 only)
- windows

I have tested it with a modified configure script from my end.  I will likely commit that configure script too.

### CODE REVIEW

**Comment by johnlaing** [comment]
Shouldn't we add 32 bit as well? I think all supported platforms should be upgraded together.

**Comment by eddelbuettel** [comment]
Fair question but as I understand it
- those libraries no longer exist / are not updated by Bbg
- because we 'overwrite in the same path' at the blp repo we can still use the old one

PS Technically, I suppose, I could peel off a 32 bit version for Windows from the zip file.  But ... CRAN does not build 32 bit binaries anymore and I think all of our users (on Windows) take binaries from CRAN.

**Comment by eddelbuettel** [comment]
Also, let's do this in stages.  _We do not have to merge now and maybe should not._  I put these up to test the parallel PR over in the other repo.

PS And eg I have not yet updated the Windows script as we currently have not Windows CI job.  Could add that...

**Comment by johnlaing** [comment]
I skimmed everything to understand the sequencing. I'm checking the deprecation branch first so we can get that merged and go from there.

**Comment by eddelbuettel** [comment]
Yes that was my idea too (and it is good to have a second set of eyes on it).  So

1. deprecations warnings to be ready for new library
2. test the new libraires, incl on Windows
3. if and when we think this is ready merge in blp repo from feature branch to main
4. ditto for Rblpapi
5. some more testing
6. CRAN release

These days we also get r-universe binaries (currently failing arm64 macos): https://rblp.r-universe.dev/Rblpapi
By default this always uses (only) the main branch but we could also pivot it to a dev branch if we want to.

**Comment by eddelbuettel** [comment]
This is now ready for review and merge so that Rblpapi can then use from the main branch rather than a feature branch (as it does now, and which works).

This PR updates the linux64. osx64 (for arm) and windows64 parts.

**Comment by johnlaing** [comment]
Have you run the full test suite with a live BBG connection on the new library? I have not been able to do that yet, and that seems like a prereq to merging into main.

**Comment by eddelbuettel** [comment]
No I cannot as I have no Bbg access.  That step relies on you so please report back whenever you have moment to try a test build.

PS Also to note that 'master in the git repo' is still a clear step before a new CRAN release.  The advantage of 'merged to master in git' is that r-universe then builds us binaries we can point people at to try.

**Comment by eddelbuettel** [comment]
> I have not been able to do that yet

Is there a way I can help you with that?  

If you build `Rblpapi` via the [feature/release_3.24.6.1](https://github.com/Rblp/Rblpapi/tree/feature/release_3.24.6.1) branch it will use the branch at the basis of this PR and test it.

**Comment by johnlaing** [comment]
I'm battling environmental constraints... afraid there's not much you can do to help there.

**Comment by eddelbuettel** [comment]
Noted.

I suggest the following:
- we merge this branch and thereby update repo blp to the new libraries: they are official, they installed / built-with cleanly on three architectures (linux for me and you, macos and windows for the builder machines of CRAN)
- we then merge in Rblpapi turning the main branch of the repo into a 'test' release
- we rely on r-universe to build us binaries (within the hour)
- we announce those on r-sig-finance and let "world at large" test them
- a week or two or whatever we think is good enough we attempt an update at CRAN

Each of these steps is reversible thanks to `git`.  Thoughts?

**Comment by johnlaing** [comment]
It's not quite that simple, since the libraries here are downloaded at build time. Updating this repo opens up the possibility that someone builds from CRAN source and gets the new libs.

I'd strongly prefer to get a full test done prior to merging - understanding that I am the blocker here. What is the rush? Particularly as you've already provided a testable arm64 binary...

**Comment by eddelbuettel** [comment]
We do *not* provide arm64.  That was a one off at mac-builder.  Those machines flush every 72 or so hours.

We would point to the libraries Bloomberg currently ships.  As opposed to the ones they shipped maybe five years ago.  I am not sure that is worse.

Also note that you demonstrated that the 'old' CRAN version works with these libraries.  It simply gets a bit of noise on deprecation that is unpleasant and that CRAN would complain about in a new upload.  There is no functional change.   As a general statement, 'current' libraries are clearly better than outdated ones, no?

**Comment by johnlaing** [comment]
We haven't demonstrated that they work - we've demonstrated that they compile. Given Bloomberg's history of violating its own documentation I would not make any assumptions about what happens beyond that.

**Comment by eddelbuettel** [comment]
I rang the bell on r-sig-finance (and CC'ed you).  Maybe someone will step forward.

**Comment by eddelbuettel** [comment]
I tried to resurrect the old macos x86_64 for macos-13 and older -- but no luck in CI.  For some reason though it _used_ to still work at GH it no longer does.  Tried a few things but no luck.  We have arm64 for macos though.

**Review by johnlaing — APPROVED** [review]

**Pull request merged**
