### PR TITLE
Update 3.8.18.1  (closes #1)

### LINKED ISSUE #1: Version update
We're a little stale these days. I also think an update would help fix Rblp/Rblpapi#214

### PR DESCRIPTION
**Pull request by johnlaing**
#1

### CODE REVIEW

**Comment by eddelbuettel** [comment]
So this replaces everything?   And in case something were to go belly-up we ... can always revert?

**Comment by johnlaing** [comment]
Yes, exactly. We could opt for some sort of versioning scheme, but that just seems awfully complicated to me -- particularly since we'll inevitably miss some versions.

We could version-tag commits and use the associated url in the configure script, if we wanted easy access to old binaries.

**Comment by eddelbuettel** [comment]
Sounds fine by me.  I guess I could just merge and then ... turn on two builds via rhub to test Windows and Linux?

**Comment by johnlaing** [comment]
I'm not familiar with rhub and its mechanics. I've tested Linux locally and no issues.

**Comment by eddelbuettel** [comment]
Run, don't walk, over here and install [this package from GitHub](https://github.com/r-hub/rhub).

These days, I just say `rhub::check_for_cran()` and moments later I have four build reports in my INBOX.  Oh, and it works on the R command-line too with pretty colors etc pp.  Make 'remote' appear 'local'.

**Comment by eddelbuettel** [comment]
Demo:

```
R> getwd()
[1] "/home/deddelbuettel/git/rblpapi"
R> rhub::check_for_cran()
─  Building package
─  Uploading package
─  Preparing build, see status at
   http://builder.r-hub.io/status/Rblpapi_0.3.5.1.tar.gz-ef772e8e137441f2b031585c77eca28e
   http://builder.r-hub.io/status/Rblpapi_0.3.5.1.tar.gz-5cc5575263bf435f86f1c262376f98d0
   http://builder.r-hub.io/status/Rblpapi_0.3.5.1.tar.gz-d3c1dfce79d849bc824754bd260176fd
   http://builder.r-hub.io/status/Rblpapi_0.3.5.1.tar.gz-5287134231b84ea4853f6a86ae9a28e0
─  Build started
─  Creating new user
─  Downloading and unpacking package file
─  Querying package dependencies
─  Installing package dependencies
─  Running R CMD check
   setting _R_CHECK_FORCE_SUGGESTS_ to false
   setting _R_CHECK_FORCE_SUGGESTS_ to true
   2: In utils::install.packages(...) :
─  using log directory 'C:/Users/USERXOnodjAtlG/Rblpapi.Rcheck'
─  using R version 3.2.5 (2016-04-14)
─  using platform: x86_64-w64-mingw32 (64-bit)
─  using session charset: ISO8859-1
─  using option '--as-cran'
✔  checking for file 'Rblpapi/DESCRIPTION'
─  this is package 'Rblpapi' version '0.3.5.1'
N  checking CRAN incoming feasibility
   Maintainer: 'Dirk Eddelbuettel <edd@debian.org>'
   Found the following (possibly) invalid URLs:
     URL: https://github.com/Rblp/Rblpapi/issues/192
       From: inst/NEWS.Rd
       Status: Error
       Message: libcurl error code 7
        Failed to connect to github.com port 443: Timed out
     URL: https://github.com/Rblp/Rblpapi/issues/85
       From: inst/NEWS.Rd
       Status: Error
       Message: libcurl error code 7
        Failed to connect to github.com port 443: Timed out
     URL: https://github.com/Rblp/Rblpapi/pull/109
       From: inst/NEWS.Rd
       Status: Error
       Message: libcurl error code 7
        Failed to connect to github.com port 443: Timed out
   
   The Date field is over a month old.
✔  checking package namespace information
✔  checking package dependencies
✔  checking if this is a source package
✔  checking if there is a namespace
✔  checking for executable files
✔  checking for hidden files and directories
✔  checking for portable file names
   Warning: running command '"C:/PROGRA~1/R/R-32~1.5/bin/x64/Rcmd.exe" INSTALL -l "C:/Users/USERXOnodjAtlG/R" --no-html "C:\Users\USERXO~1\RBLPAP~1.RCH\00_PKG~1\Rblpapi"' had status 1
   Installation failed.
   See 'C:/Users/USERXOnodjAtlG/Rblpapi.Rcheck/00install.out' for details.

E  checking whether package 'Rblpapi' can be installed
── 1 error ✖ | 0 warnings ✔ | 1 note ✖
─  Cleaning up files and user
    
R> 
```

**Pull request merged**
